sylius_paypal_webhook:
    resource: "@SyliusPayPalPlugin/Resources/config/webhook_routing.yaml"

batteries:
    path: '/batteries'
    methods: ['GET']
    defaults:
        _controller: 'App\Controller\BatteriesController::showBatteries'